from __future__ import annotations

from enum import StrEnum


class PropertyType(StrEnum):
    APARTMENT = "APARTMENT"
    HOUSE = "HOUSE"
    LAND = "LAND"
    COMMERCIAL = "COMMERCIAL"
    OTHER = "OTHER"


class CurrencyCode(StrEnum):
    EUR = "EUR"
    RSD = "RSD"


class ListingStatus(StrEnum):
    ACTIVE = "ACTIVE"
    NOT_SEEN = "NOT_SEEN"
    REMOVED = "REMOVED"
    UNKNOWN = "UNKNOWN"


class SellerType(StrEnum):
    OWNER = "OWNER"
    AGENCY = "AGENCY"
    INVESTOR = "INVESTOR"
    BANK = "BANK"
    COURT_OR_ENFORCEMENT = "COURT_OR_ENFORCEMENT"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class PropertyPipelineStatus(StrEnum):
    NEW = "NEW"
    REVIEWED = "REVIEWED"
    CALLED = "CALLED"
    VISIT_SCHEDULED = "VISIT_SCHEDULED"
    VISITED = "VISITED"
    DUE_DILIGENCE = "DUE_DILIGENCE"
    OFFERED = "OFFERED"
    NEGOTIATING = "NEGOTIATING"
    WON = "WON"
    LOST = "LOST"
    SKIPPED = "SKIPPED"
    SOLD = "SOLD"


class PropertyReviewDecision(StrEnum):
    INTERESTING = "INTERESTING"
    NOT_INTERESTING = "NOT_INTERESTING"
    UNSURE = "UNSURE"


class InteractionType(StrEnum):
    CALL = "CALL"
    MESSAGE = "MESSAGE"
    VISIT = "VISIT"
    DUE_DILIGENCE = "DUE_DILIGENCE"
    OFFER = "OFFER"
    COUNTEROFFER = "COUNTEROFFER"
    OTHER = "OTHER"


class OfferStatus(StrEnum):
    OPEN = "OPEN"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    COUNTERED = "COUNTERED"
    WITHDRAWN = "WITHDRAWN"
    EXPIRED = "EXPIRED"


class SkipReasonCode(StrEnum):
    OVERPRICED = "OVERPRICED"
    NO_MARGIN = "NO_MARGIN"
    BAD_LEGAL = "BAD_LEGAL"
    LOW_LIQUIDITY = "LOW_LIQUIDITY"
    BAD_LOCATION = "BAD_LOCATION"
    BAD_BUILDING = "BAD_BUILDING"
    HEAVY_RENOVATION = "HEAVY_RENOVATION"
    SELLER_UNREALISTIC = "SELLER_UNREALISTIC"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    FAKE_LISTING = "FAKE_LISTING"
    OTHER = "OTHER"


class PropertyOutcomeType(StrEnum):
    STILL_ACTIVE = "STILL_ACTIVE"
    REMOVED_UNKNOWN = "REMOVED_UNKNOWN"
    RELISTED = "RELISTED"
    LIKELY_SOLD = "LIKELY_SOLD"
    CONFIRMED_SOLD = "CONFIRMED_SOLD"
    BOUGHT_BY_USER = "BOUGHT_BY_USER"
    LOST_TO_OTHER_BUYER = "LOST_TO_OTHER_BUYER"
    SALE_CANCELLED = "SALE_CANCELLED"
    OTHER = "OTHER"


class DataSourceKind(StrEnum):
    SCRAPED = "SCRAPED"
    DERIVED = "DERIVED"
    LLM = "LLM"
    MANUAL = "MANUAL"
    VERIFIED_MANUAL = "VERIFIED_MANUAL"
    TRANSACTION_DATA = "TRANSACTION_DATA"
    IMPORT = "IMPORT"


class ListingEventType(StrEnum):
    DISCOVERED = "DISCOVERED"
    PRICE_CHANGED = "PRICE_CHANGED"
    TITLE_CHANGED = "TITLE_CHANGED"
    DESCRIPTION_CHANGED = "DESCRIPTION_CHANGED"
    SELLER_CHANGED = "SELLER_CHANGED"
    STATUS_CHANGED = "STATUS_CHANGED"
    REMOVED = "REMOVED"
    REAPPEARED = "REAPPEARED"
    DETAIL_CHANGED = "DETAIL_CHANGED"


class ListingRawRecordType(StrEnum):
    CARD = "CARD"
    DETAIL = "DETAIL"


class SourceHealthStatus(StrEnum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    FAILED = "FAILED"
    DISABLED = "DISABLED"


class MatchDecision(StrEnum):
    AUTO_MATCH = "AUTO_MATCH"
    MANUAL_MATCH = "MANUAL_MATCH"
    POSSIBLE_MATCH = "POSSIBLE_MATCH"
    REJECTED_MATCH = "REJECTED_MATCH"


class MatchCandidateStatus(StrEnum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class ComparableType(StrEnum):
    TRANSACTION = "TRANSACTION"
    LISTING = "LISTING"
    PROPERTY_HISTORY = "PROPERTY_HISTORY"


class ValuationStatus(StrEnum):
    SUCCESS = "SUCCESS"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class ValuationModelType(StrEnum):
    LISTING_COMPS = "LISTING_COMPS"


class LiquidityStatus(StrEnum):
    SUCCESS = "SUCCESS"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class FastSaleStatus(StrEnum):
    SUCCESS = "SUCCESS"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class AnalysisLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    UNKNOWN = "UNKNOWN"


class ReasonForSale(StrEnum):
    MOVING = "MOVING"
    MOVING_ABROAD = "MOVING_ABROAD"
    NEEDS_LIQUIDITY = "NEEDS_LIQUIDITY"
    INHERITANCE = "INHERITANCE"
    DIVORCE = "DIVORCE"
    BUSINESS_LIQUIDITY = "BUSINESS_LIQUIDITY"
    BOUGHT_ANOTHER_PROPERTY = "BOUGHT_ANOTHER_PROPERTY"
    VACANT_PROPERTY = "VACANT_PROPERTY"
    INVESTOR_EXIT = "INVESTOR_EXIT"
    TIME_DEADLINE = "TIME_DEADLINE"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class LlmAnalysisStatus(StrEnum):
    PENDING = "PENDING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    INVALID_OUTPUT = "INVALID_OUTPUT"


class RiskGateStatus(StrEnum):
    PASS = "PASS"
    VERIFY = "VERIFY"
    BLOCK = "BLOCK"


class RiskSeverity(StrEnum):
    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class RiskGateEffect(StrEnum):
    NONE = "NONE"
    VERIFY = "VERIFY"
    BLOCK = "BLOCK"


class DealAnalysisStatus(StrEnum):
    SUCCESS = "SUCCESS"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class DealScenarioType(StrEnum):
    DOWNSIDE = "DOWNSIDE"
    BASE = "BASE"
    UPSIDE = "UPSIDE"


class OpportunityAction(StrEnum):
    IGNORE = "IGNORE"
    WATCH = "WATCH"
    REVIEW = "REVIEW"
    CALL = "CALL"
    URGENT_CALL = "URGENT_CALL"


class AlertChannel(StrEnum):
    TELEGRAM = "TELEGRAM"


class AlertType(StrEnum):
    OPPORTUNITY = "OPPORTUNITY"
    OPERATIONAL = "OPERATIONAL"


class AlertStatus(StrEnum):
    PENDING = "PENDING"
    SENT = "SENT"
    FAILED = "FAILED"
    SUPPRESSED = "SUPPRESSED"


class WatchRuleType(StrEnum):
    ANY_PRICE_CHANGE = "ANY_PRICE_CHANGE"
    PRICE_BELOW = "PRICE_BELOW"
    PRICE_DROP_PERCENT = "PRICE_DROP_PERCENT"
    DESCRIPTION_CHANGE = "DESCRIPTION_CHANGE"
    SELLER_CHANGE = "SELLER_CHANGE"


class AnalysisStatus(StrEnum):
    NOT_RUN = "NOT_RUN"
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    STALE = "STALE"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
